[package]
name = "rustris"
version = "0.1.0"
authors = ["p0l1t1c1an"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
rand = "0.7"

